id: example:db1
name: Example Database 1
process_set:
- id: example:44481c13-af55-4f7e-b071-b2bec35f72d2
  has_inputs:
  - NEON_SAMP_UUID:084fa101-5f9e-4b8e-9930-63f1164fc44d
  has_outputs:
  - NEON_SAMP_UUID:e68ff983-54a4-4e4a-aa3b-3fcc95fdd765
- id: example:459baba2-a4b1-4af8-9dd8-b47d93043817
  has_inputs:
  - NEON_SAMP_UUID:5ab4ca92-69f8-4a96-8662-aac770fcfc8c
  has_outputs:
  - NEON_SAMP_UUID:a0f647ff-8887-4690-918e-feadff0c7237
- id: example:ab4dea8c-c36a-48dc-b957-f9f335994887
  has_inputs:
  - NEON_SAMP_UUID:968152e5-6b99-4bfa-9cb9-4e26a18d0719
  has_outputs:
  - NEON_SAMP_UUID:5ab4ca92-69f8-4a96-8662-aac770fcfc8c
- id: example:aabb7a92-fc1d-4f55-9cc7-f79883521390
  has_inputs:
  - NEON_SAMP_UUID:d597cb0c-061a-402c-9a28-dfaad5caf8b8
  has_outputs:
  - NEON_SAMP_UUID:084fa101-5f9e-4b8e-9930-63f1164fc44d
  - NEON_SAMP_UUID:1df7b3d8-356c-4a8a-8c5c-55d2de9ce699
  - NEON_SAMP_UUID:aaaed272-7835-4821-ac87-5a9d4ee545c5
  - NEON_SAMP_UUID:d06548a8-33d7-4b44-905c-7f25a479b7d0
  - NEON_SAMP_UUID:19d4c0d2-3aad-4115-9d24-b5f097911561
  - NEON_SAMP_UUID:3f0c3ddb-3bba-420f-af73-c5b02e5b7f8b
  - NEON_SAMP_UUID:968152e5-6b99-4bfa-9cb9-4e26a18d0719
  - NEON_SAMP_UUID:f613214b-0d37-4d09-8bd3-9025228a1f56
  - NEON_SAMP_UUID:daf4f088-feec-4d88-a729-163103927df0
- id: example:b0109547-4c46-4995-87de-6b9ba0ddee14
  has_inputs:
  - NEON_SAMP_UUID:e68ff983-54a4-4e4a-aa3b-3fcc95fdd765
  has_outputs:
  - NEON_SAMP_UUID:a9b215e5-45cb-404d-a205-21eff0d03888
  - NEON_SAMP_UUID:fede0df9-1eb9-4d1e-b8c7-670dfd25f81d
mic_dna_extraction_in_soil_dna_sample_set:
- id: NEON_SAMP_UUID:5ab4ca92-69f8-4a96-8662-aac770fcfc8c
  name: YELL_052-O-25-2.5-20190820-GEN-DNA2
  neon_sample_class: mic_dnaExtraction_in.soilDnaSampleID
- id: NEON_SAMP_UUID:e68ff983-54a4-4e4a-aa3b-3fcc95fdd765
  name: YELL_052-O-20190820-COMP-DNA1
  neon_sample_class: mic_dnaExtraction_in.soilDnaSampleID
mic_dna_extraction_in_subsample_set:
- id: NEON_SAMP_UUID:a0f647ff-8887-4690-918e-feadff0c7237
  name: YELL_052-O-25-2.5-20190820-GEN-DNA2_19S_24_2248
  neon_sample_class: mic_dnaExtraction_in.subsampleID
- id: NEON_SAMP_UUID:fede0df9-1eb9-4d1e-b8c7-670dfd25f81d
  name: YELL_052-O-20190820-COMP-DNA1_19S_31_2842
  neon_sample_class: mic_dnaExtraction_in.subsampleID
mms_metagenome_sequencing_in_processed_seq_file_name_set:
- id: NEON_SAMP_UUID:a9b215e5-45cb-404d-a205-21eff0d03888
  name: BMI_HY5W2BGXG_PLATE19S_31WELLG3.FASTQ.GZ
  neon_sample_class: mms_metagenomeSequencing_in.processedSeqFileNameID
sls_metagenomics_pooling_in_composite_sample_set:
- id: NEON_SAMP_UUID:084fa101-5f9e-4b8e-9930-63f1164fc44d
  name: YELL_052-O-20190820-COMP
  neon_sample_class: sls_metagenomicsPooling_in.compositeSampleID
sls_soil_core_collection_in_genetic_archive_sample1_set:
- id: NEON_SAMP_UUID:1df7b3d8-356c-4a8a-8c5c-55d2de9ce699
  name: YELL_052-O-25-2.5-20190820-GA1
  neon_sample_class: sls_soilCoreCollection_in.geneticArchiveSample1ID
sls_soil_core_collection_in_genetic_archive_sample2_set:
- id: NEON_SAMP_UUID:aaaed272-7835-4821-ac87-5a9d4ee545c5
  name: YELL_052-O-25-2.5-20190820-GA2
  neon_sample_class: sls_soilCoreCollection_in.geneticArchiveSample2ID
sls_soil_core_collection_in_genetic_archive_sample3_set:
- id: NEON_SAMP_UUID:d06548a8-33d7-4b44-905c-7f25a479b7d0
  name: YELL_052-O-25-2.5-20190820-GA3
  neon_sample_class: sls_soilCoreCollection_in.geneticArchiveSample3ID
sls_soil_core_collection_in_genetic_archive_sample4_set:
- id: NEON_SAMP_UUID:19d4c0d2-3aad-4115-9d24-b5f097911561
  name: YELL_052-O-25-2.5-20190820-GA4
  neon_sample_class: sls_soilCoreCollection_in.geneticArchiveSample4ID
sls_soil_core_collection_in_genetic_archive_sample5_set:
- id: NEON_SAMP_UUID:3f0c3ddb-3bba-420f-af73-c5b02e5b7f8b
  name: YELL_052-O-25-2.5-20190820-GA5
  neon_sample_class: sls_soilCoreCollection_in.geneticArchiveSample5ID
sls_soil_core_collection_in_genetic_sample_set:
- id: NEON_SAMP_UUID:968152e5-6b99-4bfa-9cb9-4e26a18d0719
  name: YELL_052-O-25-2.5-20190820-GEN
  neon_sample_class: sls_soilCoreCollection_in.geneticSampleID
sls_soil_core_collection_in_sample_set:
- id: NEON_SAMP_UUID:d597cb0c-061a-402c-9a28-dfaad5caf8b8
  name: YELL_052-O-25-2.5-20190820
  neon_sample_class: sls_soilCoreCollection_in.sampleID
sls_soil_moisture_in_moisture_sample_set:
- id: NEON_SAMP_UUID:daf4f088-feec-4d88-a729-163103927df0
  name: YELL_052-O-25-2.5-20190820-SM
  neon_sample_class: sls_soilMoisture_in.moistureSampleID
sls_soil_ph_in_ph_sample_set:
- id: NEON_SAMP_UUID:f613214b-0d37-4d09-8bd3-9025228a1f56
  name: YELL_052-O-25-2.5-20190820-PH
  neon_sample_class: sls_soilpH_in.pHSampleID
dna_sample_prep_composite_set:
- id: example:36f91159-8ff7-41e9-a53d-568885749897
  has_inputs:
  - NEON_SAMP_UUID:084fa101-5f9e-4b8e-9930-63f1164fc44d
  has_outputs:
  - NEON_SAMP_UUID:e68ff983-54a4-4e4a-aa3b-3fcc95fdd765
dna_sample_prep_simple_set:
- id: example:d3427a47-5e78-4345-90f9-86cea834b31c
  has_inputs:
  - NEON_SAMP_UUID:968152e5-6b99-4bfa-9cb9-4e26a18d0719
  has_outputs:
  - NEON_SAMP_UUID:5ab4ca92-69f8-4a96-8662-aac770fcfc8c
genetic_sample_prep_set:
- id: example:82713006-e5bb-4399-b5de-6f92653649ac
  has_inputs:
  - NEON_SAMP_UUID:d597cb0c-061a-402c-9a28-dfaad5caf8b8
  has_outputs:
  - NEON_SAMP_UUID:968152e5-6b99-4bfa-9cb9-4e26a18d0719
moisture_sample_prep_set:
- id: example:615ef808-7125-4b67-bb3d-7931a3894624
  has_inputs:
  - NEON_SAMP_UUID:d597cb0c-061a-402c-9a28-dfaad5caf8b8
  has_outputs:
  - NEON_SAMP_UUID:daf4f088-feec-4d88-a729-163103927df0
ph_sample_prep_set:
- id: example:2ca640e0-53f3-4750-a2b3-08076db2cff6
  has_inputs:
  - NEON_SAMP_UUID:d597cb0c-061a-402c-9a28-dfaad5caf8b8
  has_outputs:
  - NEON_SAMP_UUID:f613214b-0d37-4d09-8bd3-9025228a1f56
pooling_set:
- id: example:ef700498-d5a0-4dc4-af92-3dff251f3482
  has_inputs:
  - NEON_SAMP_UUID:d597cb0c-061a-402c-9a28-dfaad5caf8b8
  has_outputs:
  - NEON_SAMP_UUID:084fa101-5f9e-4b8e-9930-63f1164fc44d
sequencing_set:
- id: example:0dfed4d8-5b40-4bdc-a9f8-d1f69fbc4a12
  has_inputs:
  - NEON_SAMP_UUID:e68ff983-54a4-4e4a-aa3b-3fcc95fdd765
  has_outputs:
  - NEON_SAMP_UUID:a9b215e5-45cb-404d-a205-21eff0d03888
subsample_dna_extract_set:
- id: example:423b811a-c4d2-4c52-8e71-bc51bc26f6a6
  has_inputs:
  - NEON_SAMP_UUID:5ab4ca92-69f8-4a96-8662-aac770fcfc8c
  has_outputs:
  - NEON_SAMP_UUID:a0f647ff-8887-4690-918e-feadff0c7237
- id: example:5469b253-7226-4fd5-a206-fcd5b081b0cd
  has_inputs:
  - NEON_SAMP_UUID:e68ff983-54a4-4e4a-aa3b-3fcc95fdd765
  has_outputs:
  - NEON_SAMP_UUID:fede0df9-1eb9-4d1e-b8c7-670dfd25f81d
